# pyright: reportAny=false, reportExplicitAny=false
from typing import Any

class SettingsManager:
    path: str
    settings: dict[str, Any]
    def __init__(self, name: str, settings_directory: str | None = None) -> None: ...
    def read(self) -> None: ...
    def commit(self) -> None: ...
    def getSetting(self, key: str, default: Any = None) -> Any: ...
    def setSetting(self, key: str, value: Any) -> Any: ...
